remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Accessibility Guide"
description: "How accessibility improves Bitcoin UX for all users"

color_scheme: dark

#permalink: pretty

# --- ENVIRONMENT SWITCHING --- #
# LOCAL: When running `bundle exec jekyll serve`, leave baseurl blank ("")
# GITHUB PAGES: When pushing live, baseurl must match the repository name
# Comment/uncomment accordingly
#baseurl: ""                 # ✅ Use this line for LOCAL
baseurl: "/bitcoin-universal-design" # ✅ Use this line for GITHUB PAGES

#include:
#  - _includes/head_custom.html

# --- CUSTOM STYLING --- #
just_the_docs:
  custom_css:
    - "assets/css/style.css" # Always use {{ site.baseurl }} prefix
    - "assets/js/fix-seearch-contrast.js" # Always use {{ site.baseurl }} prefix
search_enabled: true
back_to_top: true

aux_links:
  "View on GitHub":
    - "https://github.com/jason-me/bitcoin-universal-design"

nav:
  - title: Home
    url: /index.html
  - title: Core Principles
    url: /principles.html
  - title: Accessibility Features
    url: /features.html
  - title: Practical Examples
    url: /examples.html
  - title: Workshop Guide
    url: /workshop.html
  - title: Resources
    url: /resources.html


# Force rebuild: updated 2025-04-25
